export const PRODUCT_DISPLAY_CONFIG = {
  SEARCH_SUGGESTION_LIMIT: 5,
  TOP_RATED_SIDEBAR_LIMIT: 5,
  BOUGHT_TOGETHER_LIMIT: 4,
  VIEWED_PRODUCTS_LIMIT: 10,
  RELATED_PRODUCTS_LIMIT: 10,
  POPULAR_ARTICLES_LIMIT: 3,
} as const;
